FROM eclipse-temurin:17-jre

RUN apt-get update && apt-get install -y \
    docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/digital-twin-management-*.jar app.jar

CMD ["sh", "-c", "dockerd & java -jar app.jar"]