name: Docker Image CI / CD - Digital Twin Management

env:
  DOCKER_IMAGE: digital-twin-management

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test-image:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
         submodules: 'recursive'

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 19

    - name: Cache maven repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ format('branch-{0}-{1}-maven-{2}', github.ref_name, runner.os, hashFiles('**/pom.xml')) }}
        restore-keys: |
          ${{ format('branch-{0}-{1}-maven', github.ref_name, runner.os) }}
          ${{ format('{0}-maven', runner.os) }}

    - name: Pull Digital Twin Docker Image
      run: |
        IMAGE_NAME=$(grep 'dt.deployment.docker.image' src/test/resources/application.properties | cut -d'=' -f2)
        echo "Pulling Docker image: $IMAGE_NAME"
        docker pull $IMAGE_NAME

    - name: Build Dependencies
      run: |
        cd digital-twin
        make build docker
        cd ..

    - name: Test
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
      run: |
        echo '{ "insecure-registries":["localhost:5000", "172.17.0.1:5000"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        docker info
        mvn test -Dspring.config.location=classpath:/application-test-ci.properties
