name: Docker Image CI - Digital Twin

env:
  DOCKER_IMAGE: digital-twin-management

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375  # Expose Docker daemon on port 2375
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
         submodules: 'recursive'

    - name: Cache maven repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ format('branch-{0}-{1}-maven-{2}', github.ref_name, runner.os, hashFiles('**/pom.xml')) }}
        restore-keys: |
          ${{ format('branch-{0}-{1}-maven', github.ref_name, runner.os) }}
          ${{ format('{0}-maven', runner.os) }}

    - name: Set up Docker
      run: |
        docker info

    - name: Build Dependencies
      run: |
        cd digital-twin
        make build
        cd ..

    - name: Build
      run: |
        mvn clean package

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_ORG_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest

    - name: Push the Docker image
      run: docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
