name: Docker Image CI / CD - Digital Twin Management

env:
  DOCKER_IMAGE: digital-twin-management

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375  # Expose Docker daemon on port 2375
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
         submodules: 'recursive'

    - name: Cache maven repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ format('branch-{0}-{1}-maven-{2}', github.ref_name, runner.os, hashFiles('**/pom.xml')) }}
        restore-keys: |
          ${{ format('branch-{0}-{1}-maven', github.ref_name, runner.os) }}
          ${{ format('{0}-maven', runner.os) }}

    - name: Set up Docker
      run: |
        docker info

    - name: Build Dependencies
      run: |
        cd digital-twin
        make build
        cd ..

    - name: Build
      run: |
        mvn clean package -Dmaven.test.skip=true

    - name: Extract version from pom.xml
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_ORG_TOKEN }}

    - name: Build the Docker images
      run: |
        docker build . --file Dockerfile --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }} --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
        docker build . --file Dockerfile-dind --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-${{ env.VERSION }} --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-latest

    - name: Push the Docker images
      run: |
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-${{ env.VERSION }}
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:      
      - name: SSH into VM and Deploy new Image with Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username:  ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Fail script on first error
            set -e 
            # Login to GitHub Container Registry
            echo "${{ secrets.CI_ORG_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Deploy new Image
            cd /root/modapto/system-deployment
            docker compose pull ${{ env.DOCKER_IMAGE }}
            docker compose up -d --no-deps ${{ env.DOCKER_IMAGE }}

            # Remove unused images
            docker image prune -f
            
            # Logout
            docker logout ghcr.io
