name: Docker Image CI / CD - Digital Twin Management

env:
  DOCKER_IMAGE: digital-twin-management
  FFT_CONTAINER: digital-twin-management-fft

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged
        ports:
          - 2375:2375

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
         submodules: 'recursive'

    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 19

    - name: Cache maven repository
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.sonar/cache
        key: ${{ format('branch-{0}-{1}-maven-{2}', github.ref_name, runner.os, hashFiles('**/pom.xml')) }}
        restore-keys: |
          ${{ format('branch-{0}-{1}-maven', github.ref_name, runner.os) }}
          ${{ format('{0}-maven', runner.os) }}

    - name: Pull Digital Twin Docker Image
      run: |
        IMAGE_NAME=$(grep 'dt.deployment.docker.image' src/test/resources/application.properties | cut -d'=' -f2)
        echo "Pulling Docker image: $IMAGE_NAME"
        docker pull $IMAGE_NAME

    - name: Patch aas4j with main branch
      run: |
        set -e
        git clone https://github.com/eclipse-aas4j/aas4j.git aas4j
        mvn -f aas4j/pom.xml clean spotless:apply install -DskipTests=true -Drevision=1.0.5-SNAPSHOT

    - name: Build Dependencies
      run: |
        cd digital-twin
        make build docker
        cd ..

    - name: Test & Build
      env:
        DOCKER_HOST: unix:///var/run/docker.sock
      run: |
        echo '{ "insecure-registries":["localhost:5000", "172.17.0.1:5000"] }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        docker info
        mvn package -Dspring.config.location=classpath:/application-test-ci.properties

    - name: Extract version from pom.xml
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_ORG_TOKEN }}

    - name: Build the Docker images
      run: |
        docker build . --file Dockerfile --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }} --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
        docker build . --file Dockerfile-dind --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-${{ env.VERSION }} --tag ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-latest

    - name: Push the Docker images
      run: |
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-${{ env.VERSION }}
        docker push ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:dind-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:      
      - name: SSH into VM and Deploy new Image with Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username:  ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Fail script on first error
            set -e 
            # Login to GitHub Container Registry
            echo "${{ secrets.CI_ORG_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Deploy new Image on Dev Environment
            cd /root/modapto/system-deployment
            docker compose pull ${{ env.DOCKER_IMAGE }}
            docker compose up -d --no-deps ${{ env.DOCKER_IMAGE }}

            # Deploy new Image on FFT Environment
            cd /root/modapto/fft-deployment
            docker compose up -d --no-deps ${{ env.FFT_CONTAINER }}

            # Remove unused images
            docker image prune -f
            
            # Logout
            docker logout ghcr.io
